const question = [
  "Bạn có thường xuyên bị lôi cuốn bởi những cảm tưởng, những ấn tượng mới mẻ hoặc đi tìm nguồn cảm xúc mạnh mẽ để giải buồn và làm cho mình phấn chấn không?",
  "Bạn có thường xuyên cần người ý hợp, tâm đồng để động viên an ủi không? ",
  "Bạn là người vô tư, không bận tâm đến điều gì phải không? ",
  "Bạn cảm thấy rất khó khăn khi phải từ bỏ những ý định của mình hoặc phải từ chối người khác, cả khi hoàn cảnh buộc phải làm như thế không? ",
  "Bạn có muốn trước khi làm bất kỳ việc gì cũng phải suy nghĩ, cân nhắc, không vội vàng không? ",
  "Khi đã hứa làm một việc gì, bất kể lời hứa đó có thuận lợi cho mình hay không, bạn vẫn luôn giữ lời hứa phải không? ",
  "Tâm trạng của bạn thường thay đổi, lúc vui, lúc buồn phải không? ",
  "Bạn có hay nói và hành động một cách bột phát, vội vàng không kịp suy nghĩ không? ",
  "Có khi nào bạn cảm thấy mình là người bất hạnh mà không có lý do không? ",
  "Bạn có cho mình là người không hề lúng túng, không phải mất công tìm kiếm vẫn luôn có sẵn lời giải đáp khi phải đánh giá, nhận xét một vấn đề gì đó và sẵn sàng làm tất cả để tranh luận tới cùng không? ",
  "Bạn có thấy rụt rè, e thẹn khi muốn bắt chuyện với một người khác giới dễ mến nhưng chưa quen biết không? ",
  "Đôi lúc bạn cũng nổi nóng không kiềm chế được phải không?",
  "Bạn có hay hành động một cách nông nổi, bồng bột không",
  "Bạn có hay ân hận về những lời bạn đã nói, về những việc bạn đã làm mà lẽ ra bạn không nên nói, nên làm như vậy không?  ",
  "Bạn thích đọc sách hơn là trò truyện với người khác phải không? ",
  "Bạn có dễ bị mất lòng không? ",
  "Bạn có thích luôn luôn có mặt trong nhóm, trong hội của mình không? ",
  "Có những ý nghĩ bạn giữ kín, không muốn cho người khác biết phải không? ",
  "Có đúng bạn là người đôi khi rất nhiệt tình với công việc, nhưng cũng có lúc hoàn toàn chán chường, uể oải không? ",
  "Bạn có cho rằng chỉ cần ít bạn, song là những người bạn thân là được không? ",
  "Bạn có hay mơ ước không? ",
  "Lúc người ta quát tháo với bạn, thì bạn cũng quát tháo lại phải không? ",
  "Bạn thường bị day dứt, mỗi khi mắc sai lầm phải không?",
  "Tất cả thói quen của bạn đều tốt và hợp với mong muốn của bạn phải không? ",
  "Bạn có khả năng làm chủ được tình cảm của mình và hoàn toàn vui vẻ trong các buổi họp phải không? ",
  "Bạn có cho mình là người nhạy cảm và dễ bị kích thích phải không? ",
  "Người ta cho bạn là người vui vẻ, hoạt bát phải không?",
  "Sau khi làm xong một việc quan trọng, bạn có cảm thấy rằng mình còn có thể làm việc đó tốt hơn nữa không?",
  "Ở chỗ đông người bạn thường im lặng phải không? ",
  "Đôi khi bạn cũng thêu dệt câu chuyện phải không?",
  "Bạn có hay bị mất ngủ vì những ý nghĩ lộn xộn trong đầu phải không? ",
  "Khi muốn biết một điều gì, bạn tự tìm lấy trong sách vở, chứ không đi hỏi người khác phải không?",
  "Có bao giờ bạn hồi hộp không? ",
  "Bạn có thích những công việc đòi hỏi phải chú ý thường xuyên không? ",
  "Có bao giờ bạn run sợ không?",
  "Nếu như không có người kiểm tra khi đi tàu, đi xe bạn có mua vé không? ",
  "Bạn có thấy khó chịu khi sống trong một tập thể mà mọi người hay giễu cợt nhau không? ",
  "Bạn có hay bực tức không? ",
  "Bạn có thích những công việc phải hoàn thành gấp gáp không? ",
  "Trước những sự việc có hoặc không thể xảy ra, bạn có hay hồi hộp không? ",
  "Bạn đi đứng ung dung, thong thả phải không? ",
  "Có bao giờ bạn đến nơi hẹn, hoặc đi làm, đi học muộn giờ không? ",
  "Bạn hay có những cơn ác mộng phải không? ",
  "Có đúng là bạn thích trò chuyện đến mức là không bao giờ bỏ lỡ cơ hội nói chuyện, kể cả với những người không quen biết phải không? ",
  "Có nỗi đau nào làm cho bạn làm phải lo lắng không? ",
  "Bạn có cảm thấy mình thật bất hạnh nếu như trong thời gian dài không được tiếp xúc rộng rãi với mọi người không? ",
  "Bạn có cho mình là người dễ xúc động, dễ phản ứng không? ",
  "Trong số những người quen, có người mà bạn không ưa thích họ một cách công khai phải không? ",
  "Bạn có cho mình là người hoàn toàn tự tin không? ",
  "Bạn có hay phật ý khi người khác chỉ ra những lỗi lầm trong công tác, những thiết sót trong cuộc sống riêng tư của bạn không? ",
  "Bạn có cho rằng khó có thể thực sự hài lòng trong một buổi liên hoan gặp mặt không?",
  "Sự cảm nhận rằng mình thấp kém hơn người khác có làm cho bạn khó chịu không? ",
  "Bạn có dễ dàng làm cho nhóm bạn bè của mình đang buồn chán, tẻ nhạt thành sôi nổi, vui vẻ không? ",
  "Có khi nào mà bạn nói về những điều mà bạn không am hiểu không? ",
  "Bạn có lo lắng về sức khoẻ của bản thân không? ",
  "Bạn có thích trêu đùa người khác không? ",
  "Bạn có bị mất ngủ không? ",
];

const introvert = [
  1, 3, 5, 8, 10, 13, 17, 20, 22, 25, 27, 29, 30, 32, 34, 37, 39, 41, 44, 46,
  49, 51, 53, 56,
];
const extrovert = [
  2, 4, 7, 9, 11, 14, 16, 19, 21, 23, 26, 28, 31, 33, 35, 40, 43, 45, 47, 50,
  52, 55, 57,
];
const flexible = [6, 12, 15, 18, 24, 36, 42, 48, 54];
